### ISSUE TITLE
HTTP POST

### ISSUE THREAD

**Issue by bird1015** [kymjs/RxVolley#1]
如何发送HTTP POST数据？

**Comment by kymjs** [comment]
RxVolley.httpMethod(RxVolley.Method.POST)    
 如果不传，默认为GET，可选项： POST/PUT/DELETE/HEAD/OPTIONS/TRACE/PATCH

**Comment by ZongweiBai** [comment]
支持HTTPS吗？

**Comment by kymjs** [comment]
@ZongweiBai 如果不设置，默认信任全部的https证书。可以传入自定义```SSLSocketFactory```  
详细查看代码：[HttpConnectStack](https://github.com/kymjs/RxVolley/blob/master/RxVolley/rxvolley/src/main/java/com/kymjs/rxvolley/http/HttpConnectStack.java)
