### ISSUE TITLE
下载功能貌似不太好用

### ISSUE THREAD

**Issue by Qrilee** [kymjs/RxVolley#10]
测试了几种方法，也替换了好些个url，就博主的url正常下载- -，希望博主改进一下

**Comment by kymjs** [comment]
有下载异常的URL吗，提供一下，看看什么原因。

**Comment by Qrilee** [comment]
在安卓市场上随便找的一个qq下载链接，拿okhttp下载没问题，RxVolley的话不知道是不是响应超时的问题

**Comment by Qrilee** [comment]
http://apk.r1.market.hiapk.com/data/upload/apkres/2015/12_28/21/com.tencent.mobileqq_092906.apk

**Comment by kymjs** [comment]
Volley 对大文件的支持不是很好，可以在初始化```RxVolley```的时候使用```OkHttp```来请求  
```java
RxVolley.setRequestQueue(RequestQueue.newRequestQueue(CACHE_FOLDER,
        new OkHttpStack(new OkHttpClient())));
```

**Comment by Qrilee** [comment]
了解，感谢解答
