### ISSUE TITLE
文件上传下载疑问

### ISSUE THREAD

**Issue by liang530** [kymjs/RxVolley#11]
文件下载支持断点下载，暂停，和继续下载功能吗？
文件上传支持多个文件上传且多个文件用同一个key接收吗？因为很多时候不知道用户要上传多少张，后台就会以数组方式接收……

**Comment by kymjs** [comment]
支持断点续传。  
可直接调用下载方法```RxVolley.download()```
取消的时候直接调用```RxVolley.getRequestQueue().cancelAll(url);```
恢复直接再次下载即可自动续传。

多文件上传支持，内部不是使用的```Map```，可以直接采用相同的key。
如需要了解内部实现，可查看[HttpParams](https://github.com/kymjs/RxVolley/blob/master/RxVolley/rxvolley/src/main/java/com/kymjs/rxvolley/client/HttpParams.java)

**Comment by liang530** [comment]
谢谢
