### ISSUE TITLE
导入demo，出错java.lang.RuntimeException: RequestQueue-> DiskBasedCache cache dir error

### ISSUE THREAD

**Issue by weimanleung** [kymjs/RxVolley#12]

**Comment by kymjs** [comment]
请检查缓存文件路径，出错原因查看代码[newRequestQueue](https://github.com/kymjs/RxVolley/blob/master/RxVolley/rxvolley/src/main/java/com/kymjs/rxvolley/http/RequestQueue.java) 底部```newRequestQueue(File, IHttpStack)```  

建议项目中使用```context.getCacheDir()```作为缓存目录

**Comment by sauravexodus** [comment]
How did you solve this?

**Comment by sauravexodus** [comment]
This error only reproduces in Android Marshamallow
