### ISSUE TITLE
使用RxVolley的getResult得到Observable<Result> 没有error的回调

### ISSUE THREAD

**Issue by lsp19880926** [kymjs/RxVolley#13]
如题，没有error的回调 请求失败拿不到响应

**Comment by yinCheng3161** [comment]
我也在头疼这个问题，例如用户网络已经连接，但基本没有信号，请求会失败，进度条一致在显示... 不用RxJava，用HttpCallback在onFailure用可以处理，如果用RxVolley会很棘手....

**Comment by yinhaojun** [comment]
楼上的解决了吗？  好像确实网络不行的时候，得不到超时的回调

**Comment by kymjs** [comment]
问题已经修复，请使用```1.1.0```版本
