### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by a395726103** [kymjs/RxVolley#17]
我们项目有一个登陆接口，用的post请求，默认不使用缓存，但是登陆的时候，只要用户名或者密码输错了一次，后面输入正确的用户名或者密码的时候，不会再去请求服务端，一直是返回用户名或者密码错误的状态，就算请求完了调用RxVolley.getRequestQueue().getCache().clear()也没用，只有重新new HttpParams()之后，输入正确的用户名和密码才能正常登陆。

**Comment by kymjs** [comment]
没有发现这种问题，请查看gradle引入的版本是否为最新版本，以及确认是否通过post请求传递，是否设置了缓存开启。
