### ISSUE TITLE
发起POST请求, 参数没有生效

### ISSUE THREAD

**Issue by chenjia1992** [kymjs/RxVolley#19]
HttpParams params = new HttpParams();
        params.put("username", GPSData.DriverId);
        params.put("password", GPSData.password);
        Observable<Result> result = new RxVolley.Builder()
                .url(api)
                .httpMethod(RxVolley.Method.POST)
                .params(params)
                .contentType(RxVolley.ContentType.JSON)
                .getResult();
        result.map(new Func1<Result, String>() {
            @Override
            public String call(Result result) {
                return new String(result.data);
            }
        }).subscribe(new Action1<String>() {
            @Override
            public void call(String s) {
                Log.e("ll", "result===>" + s);
            }
        });

通过charles看request, 没有看到对应的请求参数

**Comment by kymjs** [comment]
```.contentType(RxVolley.ContentType.JSON)```
contenttype选择FORM，或者如果是以JSON作为参数，使用
```params.putJsonParams()```

**Comment by chenjia1992** [comment]
嗯嗯, 刚刚没有看到, 谢谢您


原始邮件
发件人:张涛notifications@github.com
收件人:kymjs/RxVolleyRxVolley@noreply.github.com
抄送:chenjia1992androidchen@yeah.net
发送时间:2016年3月28日(周一) 14:06
主题:Re: [RxVolley] 发起POST请求, 参数没有生效 (#19)


contenttype选择FORM，或者如果是以JSON作为参数，使用 ```params.putJsonParams()```
