### ISSUE TITLE
get请求cache为true时，RxJava偶尔没有响应

### ISSUE THREAD

**Issue by ZongweiBai** [kymjs/RxVolley#21]
在Get请求并设置cache为true的时候，短时间间隔下再次发起请求，RxJava的订阅没有响应，如果设置cache为false的时候，就不存在这个问题。代码如下：
‘String requestUrl = APIConstData.GetContentByDate + DateUtils.getDate();
        observable = new RxVolley.Builder()
                .url(requestUrl)
                .httpMethod(RxVolley.Method.GET)
                .contentType(RxVolley.ContentType.FORM)
                .shouldCache(false)
                .encoding("UTF-8")
                .getResult();
        mSubscription = observable
                .map(new Func1<Result, ContentData>() {
                    @Override
                    public ContentData call(Result result) {
                        ContentData contentData = JSON.parseObject(result.data, ContentData.class);
                        return contentData;
                    }
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .doOnError(new Action1<Throwable>() {
                    @Override
                    public void call(Throwable throwable) {
                        mSwipeRefresh.setRefreshing(false);
                        ToastUtils.showShort(getContext(), "请求出错");
                    }
                })
                .subscribe(new Action1<ContentData>() {
                    @Override
                    public void call(ContentData contentData) {
                        mListData.clear();
                        mListData.addAll(contentData.getPosts());
                        mTodayAdapter.notifyDataSetChanged();
                        if (mSwipeRefresh != null) {
                            mSwipeRefresh.setRefreshing(false);
                        }
                        ToastUtils.showShort(getContext(), "请求成功");
                    }
                });`

**Comment by yinCheng3161** [comment]
我最近也遇到了这个问题，同时发送多了请求，getResult确实可以拿到结果，但执行subscribeOn后个别返回的Subscription偶尔会出现为null的情况，尤其是在TV设备上会出现。

**Comment by kymjs** [comment]
@ZongweiBai 已经修复

@Cloudez 你的问题应该是返回了失败，但是你没提供失败的回调。参照 1.1.0 版本使用中 rxjava 篇的```subscribe()```参数   http://rxvolley.mydoc.io/
