### ISSUE TITLE
POST 请求

### ISSUE THREAD

**Issue by gybin02** [kymjs/RxVolley#25]
POST 请求 ，如果参数使用下面的构造，发现， POST内容是空的。。
这个 太容易混淆，骗人了。。
HttpParams params = new HttpParams();

//http header, optional parameters
params.putHeaders("cookie", "your cookie");
params.putHeaders("User-Agent", "rxvolley"); 

//request parameters
params.put("name", "kymjs");
params.put("age", "18");

**Comment by kymjs** [comment]
请分清header和body
