### ISSUE TITLE
使用RxJava时，网络已连接，但没有流量，请求发出去后，进度条一直显示，如何关闭进度条？

### ISSUE THREAD

**Issue by yinCheng3161** [kymjs/RxVolley#26]
RxVolley结合RxJava时，测试中发现这样一个问题，网络已经连接，但关闭了流量（360WIFI可把连接用户拉进黑名单，从而实现网络连接，但流量被关闭），这时候发送请求并显示进度条，会造成进度条一致显示，如何停止请求并关闭进度条？这个貌似需要在getResult之前操作？

**Comment by kymjs** [comment]
自己手动设置超时时间
