### ISSUE TITLE
jsonPost无法传参

### ISSUE THREAD

**Issue by lvtanxi** [kymjs/RxVolley#27]
HttpParams params = new HttpParams();
        params.put("loginName", "00000001");
        params.put("loginPwd", "123456");
        RxVolley.jsonPost("http://10.13.2.80:8080/common/login", params, new HttpCallback() {
            @Override
            public void onSuccess(String t) {
                Loger.debug("请求到的数据:" + t);
            }
            @Override
            public void onFailure(int errorNo, String strMsg) {
                super.onFailure(errorNo, strMsg);
                Loger.debug("strMsg:" + strMsg);
            }
        });
这样请求的时候参数没办法传递上去

**Comment by kymjs** [comment]
用post()
