### ISSUE TITLE
how to call cancelAll on the RequestQueue?

### ISSUE THREAD

**Issue by LOG-TAG** [kymjs/RxVolley#3]
Advantage of Google volley is the customized request calls with control over network request like we can call mRequestQueue.cancelAll(tag);   can you explain how we can do that in this RxVolley?

**Comment by kymjs** [comment]
RxVolley base on Google Volley, you can use  ```RxVolley. getRequestQueue()``` get the ```RequestQueue``` object.   
view it on code [RxVolley line:57](https://github.com/kymjs/RxVolley/blob/master/RxVolley/rxvolley/src/main/java/com/kymjs/rxvolley/RxVolley.java) and [RequestQueue line:219](https://github.com/kymjs/RxVolley/blob/master/RxVolley/rxvolley/src/main/java/com/kymjs/rxvolley/http/RequestQueue.java)
