### ISSUE TITLE
使用RxVolley.download下载文件返回Unexpected response code 206

### ISSUE THREAD

**Issue by longzaitian** [kymjs/RxVolley#32]

**Comment by yousql** [comment]
我也遇到同样的问题~~~

**Comment by Fomove** [comment]
我也遇到同样的问题~

**Comment by kymjs** [comment]
使用```1.1.4```版本

**Comment by LiuGuiLinAndroid** [comment]
我使用的是：compile 'com.kymjs.rxvolley:rxvolley:1.1.4'
但是依然碰到这个问题：Unexpected response code 206 for http://app.mi.com/download/61904

**Comment by shisan** [comment]
我使用的是 compile 'com.kymjs.rxvolley:rxvolley:1.1.4'，依然有这个问题。换了几个不同的下载地址，依然问题存在，  在虚拟机里正常，真机里有这个问题。

**Comment by kymjs** [comment]
由于服务端不支持断点续传造成服务器返回了206。  
具体解释请自行搜索```http响应码206```   
下个版本将会加入判断，如果服务器不支持则不使用断点续传。

**Comment by shisan** [comment]
请问在android端，怎么设置不使用断点续传？

**Comment by shisan** [comment]
如果是服务端的问题，为什么真机上不行，模拟器上确正常了？
