### ISSUE TITLE
请求的参数无法打印出来！

### ISSUE THREAD

**Issue by Xzuing** [kymjs/RxVolley#33]
httpParams.put(); 进去的参数无法打印！我也是醉了

**Comment by kymjs** [comment]
描述详细一些，怎么打印的，requesttype是什么，要打印什么。

**Comment by Xzuing** [comment]
抱歉哈，之前没描述清楚~意思就是如何打印httpParams.put()进去的参数呢？

**Comment by kymjs** [comment]
httpParams.getUrlParams();
getJsonParams();
