### ISSUE TITLE
乱码问题

### ISSUE THREAD

**Issue by zeroztguo** [kymjs/RxVolley#35]
这样的写法有错误吗，各种编码乱码都无法解决

new RxVolley.Builder()
                .url(url)
                .httpMethod(RxVolley.Method.GET)
                .params(params)
                .encoding("gb2312")
                .callback(new HttpCallback() {
                    @Override
                    public void onSuccess(String t) {
                        super.onSuccess(t);
                        Logger.d(t);
                     }

                    @Override
                    public void onFailure(int errorNo, String strMsg) {
                        super.onFailure(errorNo, strMsg);
                        Logger.d(errorNo);
                    }
                })
                .doTask();

**Comment by kymjs** [comment]
使用utf-8
