### ISSUE TITLE
Error:(24, 17) 错误: 无法为最终变量CACHE_FOLDER分配值

### ISSUE THREAD

**Issue by tianshaokai** [kymjs/RxVolley#4]

**Comment by kymjs** [comment]
没看懂你说的什么意思。  
```CACHE_FOLDER``` 为常量，仅用作默认缓存文件夹使用。  
如果你想自定义缓存文件夹，可以看文档中的使用方式: [http://rxvolley.mydoc.io/](http://rxvolley.mydoc.io/)

**Comment by tianshaokai** [comment]
我把项目下载下来build 的时候报这个错误
