### ISSUE TITLE
在android模拟器API23版本上运行会导致程序崩溃

### ISSUE THREAD

**Issue by gdmec07140541** [kymjs/RxVolley#45]
比如，我用rxvolley获取网络数据进行登录注册等操作，在api23的模拟器上操作会直接崩溃的，但我用volley的话就不会崩溃，其他android版本的模拟器目前还没试过。我在公司，整个项目都是用rxvolley的，因为它真的很好，恳请您有空的话，修复一下这个bug，不胜感激！

**Comment by kymjs** [comment]
并没有发现这种问题。
请详细描述问题情况，设置项、版本、缓存路径、权限、报错信息。

**Comment by kymjs** [comment]
查明：API 23以后 SD 卡写权限需要动态注册，
 使用```compile 'com.kymjs.rxvolley:rxvolley:1.1.0'```版本或者设置默认缓存文件夹为包内存储均可解决。
