### ISSUE TITLE
maxSdkVersion=18

### ISSUE THREAD

**Issue by yinhaojun** [kymjs/RxVolley#46]
你好！首先你的请求库写的非常好，我在项目中使用了。但是让我郁闷了很久，这个库你添加了WRITE_EXTERNAL_STORAGE权限，同时将maxSdkVersion设置成了18，api大于18的设备获取不到WRITE_EXTERNAL_STORAGE权限，无法对sd卡进行操作。该问题浪费了我足足一天多，希望你能够看下这个问题。并做相应的调整。

**Comment by kymjs** [comment]
```1.1.4```版本已修复
