### ISSUE TITLE
RxVolley对http响应头的处理有问题

### ISSUE THREAD

**Issue by passerbya** [kymjs/RxVolley#49]
类com.kymjs.rxvolley.http.Response和com.kymjs.rxvolley.client.HttpCallback中对http响应header的处理使用的是Map，而http响应header的名字是可以重复的，比如有多个Set-Cookie，服务器下发多个cookie，例如附件中访问git.oschina.net后下发了四个Set-Cookie
![qq 20170108141037](https://cloud.githubusercontent.com/assets/758077/21800894/7b5942f6-d75a-11e6-8c0a-007c3d4a563c.png)

**Comment by kymjs** [comment]
下个版本修复

**Comment by kymjs** [comment]
没有此问题，在获取数据时已经做过数据合并。

**Comment by passerbya** [comment]
那怎么解析出来cookie呢？cookie的不同属性就用;分隔的，参考我的截图。就不说cookie了，怎么保证其他的header字段里面没有你用的分隔符呢？一般http工具返回的headers都是数据或者list

**Comment by Fionashow** [comment]
你好，在ijkPlayer issues看到你这边做过外挂字幕，请问可否能提供方式请教一下呢

**Comment by Fionashow** [comment]
你好，在ijkPlayer issues看到你这边做过外挂字幕，请问可否能提供方式请教一下呢
