### ISSUE TITLE
上传文件时,有多个表单,怎么只设置文件的ContentType?

### ISSUE THREAD

**Issue by tream** [kymjs/RxVolley#8]
通过现有的HttpParams.setContentType会将所有的表单项的ContentType都设置成一样的吧,服务器读取就出错了

**Comment by kymjs** [comment]
如果我没理解错，你是想传递多个文件和字符串的集合，  
多次调用可以传递多个文件或字符串  
```
params.put(key, file);
params.put(key, string);
```

**Comment by tream** [comment]
比如我上传一个MP3文件,需要单独设置他的contentType为audio/mp3,因为服务器会验证这个contentType

**Comment by tream** [comment]
如果用setContentType方法的话所有表单在输出的时候contentType都变成了我设置的,然后服务器就报解析不到表单中的token

**Comment by kymjs** [comment]
了解你的意思了。  
两种方法，一种实现简单但写起来麻烦，不同的type分开post；  
另一种，自定义一个 ```Request``` 类，重新```getBody```方法和```getBodyContentType```达到你的需求。  

在 Volley 中，post数据时会调用如下方法，详情查看Volley代码：[HurlStack](https://github.com/mcxiaoke/android-volley/blob/master/src/main/java/com/android/volley/toolbox/HurlStack.java)或者RxVolley代码：[HttpConnectStack](https://github.com/kymjs/RxVolley/blob/master/RxVolley/rxvolley/src/main/java/com/kymjs/rxvolley/http/HttpConnectStack.java)  

```java
private static void addBodyIfExists(HttpURLConnection connection, Request<?> request)
            throws IOException, AuthFailureError {
        byte[] body = request.getBody();
        if (body != null) {
            connection.setDoOutput(true);
            connection.addRequestProperty(HEADER_CONTENT_TYPE, request.getBodyContentType());
            DataOutputStream out = new DataOutputStream(connection.getOutputStream());
            out.write(body);
            out.close();
        }
    }
```

**Comment by kymjs** [comment]
@tream 使用1.04的依赖，```HttpParams``` 添加了一个方法

```java
 /**
     * 添加二进制文件参数
     *
     * @param key           参数key
     * @param rawData       二进制参数body
     * @param type          参数的contentType
     * @param encodingBytes 参数的字符集
     * @param fileName      二进制文件名,可以为空
     */
    public void put(final String key, final byte[] rawData, String type,
                    byte[] encodingBytes, String fileName) {}
```
